### ISSUE TITLE
[BUG] Save image and animation picture

### ISSUE THREAD

**Issue by gponceau** [state-of-the-art/BlendNet#119]
### Issue description:
When I run an image task or an animation task, there are an error when the job is ended. In fact, it can't save the picture. A already try everything in the output field in the output properties. I tried "//out/img.jpg", "//out/", "C:/Users/[name]/Documents", etc... But nothing works...

### Environment:
* **Application version**: 0.3.3
* **Blender client version**: 2.90.1
* **Blender worker version**: 2.90.1
* **OS**: Windows 10

### Steps to reproduce:
1. Run Blender, Manager and Agent on an other computer
2. Open project
3. In Output Properties, I specify the output field
4. Run Image Task or Animation Task
5. The picture calculates...
5. Ath the end, I see e"ERR"

### Expected behavior
I expected to see the picture saved on the folder I choosed

**Comment by rabits** [comment]
@gponceau, could you please confirm the version you're using? Also that will be great if you can attach some logs (service ones (for manager/agents), task messages, task info - all of them are available through BlendNet UI. Maybe some screenshots?). Also please describe your environment - what the provider you using for example. Maybe the blend scene you using is somehow not processed properly - check with some simple one to figure that out.

Also could recommend to go through the first steps, it should describe how the BlendNet is working and cut the most of the issues you can experience in the first time: https://github.com/state-of-the-art/BlendNet/wiki/HOWTO%3A-First-steps . Also on the youtube channel you can find the demo videos with going through the rendering process: https://www.youtube.com/channel/UCzDjxhdrkoDdyGWDNs-j7hw/videos

**Comment by gponceau** [comment]
Sorry for the version of Blendnet. It's 0.3.3. For the rest, it's ok : Windows 10 and Blender 2.90.1.
I attached all logs and messages I found. Thank you for helping me.
![AgentLOG](https://user-images.githubusercontent.com/72932801/99067389-ec0ee800-25aa-11eb-8a5c-d5cae956f7cd.JPG)
![ManagerLOG](https://user-images.githubusercontent.com/72932801/99067390-eca77e80-25aa-11eb-9db6-1db12eb54cb8.JPG)
![TaskInfo](https://user-images.githubusercontent.com/72932801/99067391-ed401500-25aa-11eb-93e6-242e3bb11d84.JPG)
![TaskMessages](https://user-images.githubusercontent.com/72932801/99067392-ed401500-25aa-11eb-9767-cad74a6a3110.JPG)
![TaskPreview](https://user-images.githubusercontent.com/72932801/99067394-edd8ab80-25aa-11eb-881e-45cafa49748b.JPG)

And I already watch the video and the First Steps Wiki. ;-)

**Comment by rabits** [comment]
Ok, you see in the task info - `state_error_info` - seems there is some issue with compositing process (on the Manager node for v0.3.3) encoding... Could you please check - where you using non-unicode symbols?

The things needed to continue debug:
* Also please describe your environment - what the provider you using for example.
* Compositing process - looks like it contains something (like path or node name) that blendnet not processing correctly...
* The logs from manager service (better to save text file than make screenshot, that will give the full context for debug)

**Comment by gponceau** [comment]
I don't know what are non unicod symbol :-/
• My provider is local (my own resources). I don't know what else you need to describe my environment : I think I tell all I know to describe that :)
• Maybe. But the scene is incredibly simple to test the add-on. It's just a cube with a simple material (without texture) and the only map is a HDR named "Nuageux-Ocean02_8k.hdr". Will this helpful if I send you the .blend ? And if yes, how can I do that for you ? By e-mail ?
• I attached you the text manager log just below
Thank you for helping me
[manager_log.txt](https://github.com/state-of-the-art/BlendNet/files/5548817/manager_log.txt)

**Comment by rabits** [comment]
Ok, the `local provider`, that's a good start) Because the cloud providers (GCP/AWS) are slightly different and local one requires more information about the setup...

Yeah if you can attach the blend file - and I will try to reproduce the issue). I think you can't attach the dependency (usually such HDR's are not free), so I think if you will pick the blend file itself and attach it right here (you can see `Attach files by dragging...` below the comment input) - that will be just enough.

Yep, the log from manager is extremely helpful! Thank you) It slightly describes the environment, for example:
* you followed the instructions in wiki - that's great, but looks like you using the same settings (and most probably you running the Manager on the same Client node) - so maybe they causing the issue, you can try to disable reading of your user settings on the Manager by
* you using french locale on your windows, so that could cause some issues if you used some non-ASCII symbols somewhere
* the compositing tree looks quite simple

So my assumption about the error - is those warnings from `_processOutputs` function [here](https://github.com/state-of-the-art/BlendNet/blob/v0.3.3/BlendNet/ManagerTask.py#L246). The userprefs are causing the blender to fail (produce [non-zero return here](https://github.com/state-of-the-art/BlendNet/blob/v0.3.3/BlendNet/ManagerTask.py#L239)):
```
WARN: The process seems not ended well:
WARN: Process stderr:
```
Looks like they are trying to print some errors from stderr and can't do that, because it contains some weird chars. Overall you can try to play around the `.decode()` part of the line, for example:

1. locate [BlendNet/ManagerTask.py line 246](https://github.com/state-of-the-art/BlendNet/blob/v0.3.3/BlendNet/ManagerTask.py#L246) in your local dist:
   ```python
   for line in errs.decode().split('\n'):
   ```
2. Adjust it like:
   ```
   for line in errs.split(b'\n'):
   ```
   Or remove lines 246-247
3. Restart the Manager and run the render again

That should fix the issue for you, and we can go from that.

**Comment by gponceau** [comment]
Hi,
Here you find attached the .zip with the blend (it's impossible to join directly the blend file on github) ans I remove the HDR to attach the file because there are a 10MB limit. The render doesn't work even without the HDR ;-)
[untitled.zip](https://github.com/state-of-the-art/BlendNet/files/5552971/untitled.zip)

• Weird... Because the manager and the client or not the same computer. But I just copy-paste the folder like it says on the wiki.
• Yes, I'm french so it's normal ^^ Maybe it's the problem but I avoid the french character (like é or some others) to avoid problems. Si I don't know if it's the problem :-/ But maybe I forgot somewhere
• Yeah. Because the render made errors on my complicated scenes, I wanted to try on a simple one after that and there is the same problem. I hope when I tried on the simple one and it works that it will work on the complicated one :)

The first solution you propose (adjust line 246) doesn't work. And here is the manager log with this solution : 
[manager_log_sol1.txt](https://github.com/state-of-the-art/BlendNet/files/5553044/manager_log_sol1.txt)
The second solution (remove line 246 and 247) works properly !!!! **Thank you** ! And I attach you the manager log just in case you need it : 
[manager_log_sol2.txt](https://github.com/state-of-the-art/BlendNet/files/5553056/manager_log_sol2.txt)

And now, because the simple scene works properly to save the render, I decided to start the render on the complicated scene and I think there is another problem (or maybe it's linked). When the render is done, it lets "RUNNING" at 100% and 3 hours later, it stills the same... I launch the render around 11.00am so the log of the manager doesn't go until that so I attach you the log with the suit of the first render with the same one restarts at 2.06pm.
[manager_log_complicatedscene.txt](https://github.com/state-of-the-art/BlendNet/files/5553706/manager_log_complicatedscene.txt)

I hope you could help

**Comment by rabits** [comment]
Ahah, nono french is not a problem for sure)) The problem is how the BlendNet processing output from non-UTF-8 stderr/stdout of Blender. I think Blender prints something to stdout/stderr that cant be processed on french locale (and probably the others too). Seems not related to the blend project you using.

Ok, so we localized the first issue and I will prepare fix for it. The complicated scene issue, but I don't see where it started - probably there was some issues? That will be great to see the whole Manager log of rendering the complicated task if it's possible (you can skip the repeated lines of requests or zip the log to fit 10MB limit). Also if there is some errors you can locate (like task status errors / task messages).

Also to not capture the Manager log from console - you can use button `Service Log` like described here: https://github.com/state-of-the-art/BlendNet/wiki/If-you-stuck-with-an-issue#handy-get-log-for-manager-and-agents-services and save the popped-up text to a file and attach here.

**Comment by gponceau** [comment]
Thank you for your tip ;-)
So here is the manager log with the start of the render :)  The render was at 100% at 16:12:36 and that's it. It never saves.
[blendnet-test-manager_201118-161327.log](https://github.com/state-of-the-art/BlendNet/files/5560945/blendnet-test-manager_201118-161327.log)

**Comment by rabits** [comment]
Yeah, that's weird - I see it's completing the Agent subtask, but for some reason not starting the compose operation...
```
DEBUG: Retreive details about the task MSCWorldclassmapsincluded-2011181509-51-bGk_0 execution
INFO: The agent task MSCWorldclassmapsincluded-2011181509-51-bGk_0 was completed
```
Maybe there is some issue on the Agent? Could you please attach the Agent log? Also please check the task messages/info on errors/warnings and attach if it's possible. Better to add the Manager log too (if you restarting the task for each try) to get the whole picture of what's happening...

**Comment by rabits** [comment]
Ok, prepared the dev build with fixes of every decode I found in the codebase, could you check it please (for all the BlendNet components of course): https://846-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.4-ebc9936.zip

**Comment by gponceau** [comment]
Thank you again for your help. I join you just below the manager and agent (node01) log, and the task info. Task messages and task details send me to the agent log. Here is with version 0.3.3 installed on manager and agent.
[manager_0.3.3.log](https://github.com/state-of-the-art/BlendNet/files/5565444/manager_0.3.3.log)
[node01_0.3.3.log](https://github.com/state-of-the-art/BlendNet/files/5565445/node01_0.3.3.log)
![TaskInfo](https://user-images.githubusercontent.com/72932801/99641903-29f88a00-2a4b-11eb-9adc-d045b4b06e08.jpg)
Here is the same with 0.3.4 version wich it doesn't work as well for the complicated scene :
[node01_0.3.4.log](https://github.com/state-of-the-art/BlendNet/files/5565571/node01_0.3.4.log)
[manager_0.3.4.log](https://github.com/state-of-the-art/BlendNet/files/5565572/manager_0.3.4.log)
And the 0.3.4 version doesn't work for the simple scene either... Here is the manager and agent log for the simple cube scene on my computer...
[manager_cubescene_0.3.4.log](https://github.com/state-of-the-art/BlendNet/files/5565586/manager_cubescene_0.3.4.log)
[node01_cubescene_0.3.4.log](https://github.com/state-of-the-art/BlendNet/files/5565588/node01_cubescene_0.3.4.log)
I'm so sorry for the bad news...

**Comment by rabits** [comment]
No worries - together we will figure it out) Thank you for your help - I really appreciate your reports, without them that will be much harder to fix (and even know about the issue :)

So will check the logs carefully and come back asap with some thoughts.

**Comment by rabits** [comment]
Checked the latest (simple scene) and see that compositing operation was completed just 8 secs prior to you get the Manager log:
```
20.11.19 10:00:48.718000	DEBUG: Compositing completed for task "cube-2011190900-0-Kgh"
```

Also seems the log buttons are not working well enough - alot of empty lines, need to check what's wrong there... So I think I need to fix the issue with logs first, otherwise it's hard to tell what is missed there.

**Comment by rabits** [comment]
@gponceau seems I can't fix the logs received via "Service Log" buttons right now - so could you please run the manager/agent, run the complex scene and attach the console output (I think it will be better, than the service logs).

**Comment by rabits** [comment]
Ok, just got the time to reproduce the issue with `service logs` on windows - will try to got the better solution instead of the existing one.

**Comment by rabits** [comment]
Yep, windows just writes with the same timestamp (that is used as key) - so overrides the previous messages. Will create the better dev version soon.

**Comment by rabits** [comment]
Ok, prepared the better version to get the logs on windows via `Service Log` log button: https://851-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.4-bcec908.zip

@gponceau could you please try to render the complex scene again with it and capture the logs from Manager/Agent.

**Comment by gponceau** [comment]
Hi !
Sorry for the delay. I was pretty busy this week.
So. I'm not sure I understand what you want. So I used your new blendnet 0.3.4 sent in the last message and I attach you the service log from the complex scene directly from Blender (and not from console). I hope it was what you want ^^

I think maybe the problem is due to an interaction with another plug-in I have : RenderBurst. I watch a lot of time his name in the logs... Is that possible ?

[ComplexScene-2011271050-51-H33messages_201127-1156.log](https://github.com/state-of-the-art/BlendNet/files/5607472/ComplexScene-2011271050-51-H33messages_201127-1156.log)
[ComplexScene-Node01_201127-115828.log](https://github.com/state-of-the-art/BlendNet/files/5607473/ComplexScene-Node01_201127-115828.log)

**Comment by rabits** [comment]
Hi @gponceau , no worries about the delay and sorry about the confusion - in the latest build (blendnet-0.3.4-0152b6a.zip) I fixed the issue with hidden logs on windows platform - that's why I asked you to run the test again over it. And now I see some weird issues there, that probably cause the crashes, check your logs:

* Seems like this one is related to some custom settings you have in the Blender default settings folder, not sure if it's the core issue, but probably is a good place to look on your side - try to use BlendNet without this plugin and check how it will go or you can try to put it in the Agent/Manager blender dist folder (somewhere in the plugins, not sure how it should be installed):
   ```
   20.11.27 11:50:46.071000	>err>> Traceback (most recent call last):>std>> DEBUG: Disabled stdout/stderr buffering
   20.11.27 11:50:46.071000	>err>>   File "C:\Users\gponc\Documents\Blendnet\dist\blender\2.90\scripts\modules\addon_utils.py", line 351, in enable
   20.11.27 11:50:46.071000	
   20.11.27 11:50:46.071000	>err>>     mod = __import__(module_name)
   20.11.27 11:50:46.071000	>err>> ModuleNotFoundError: No module named 'RenderBurst'
   ```
* The blender crashes, so you can check with blender devs about this crash.txt file (or attach it here and I will check if it's related somehow to BlendNet, but this is probably not our case - most probably it's because of the absence of the RenderBurst plugin):
   ```
   20.11.27 11:53:05.749000	>std>> Fra:51 Mem:19686.75M (Peak 20124.75M) | Time:02:31.25 | Mem:13387.89M, Peak:13826.07M | Scene, View Layer | Finished
   20.11.27 11:53:05.811000	>err>> Error   : EXCEPTION_ACCESS_VIOLATION
   20.11.27 11:53:05.811000	>err>> Address : 0x00007FF75F6C0D43>std>> Writing: C:\Users\gponc\AppData\Local\Temp\MSCWorldclass_mapsincluded.crash.txt
   20.11.27 11:53:05.811000	>err>> Module  : blender.exe
   20.11.27 11:53:05.811000	
   20.11.27 11:53:05.811000	>err>> Thread  : 00003510
   ```

**Comment by rabits** [comment]
And seems you added just 2 same logs for the Agent, but to complete the debug I need the service log from the Manager too.

**Comment by gponceau** [comment]
Hi @rabits 
I delete RenderBurst to see what happend and here what I have : 
[blendnet-test-manager_201128-103802.log](https://github.com/state-of-the-art/BlendNet/files/5610358/blendnet-test-manager_201128-103802.log)
[Node01_201128-103934.log](https://github.com/state-of-the-art/BlendNet/files/5610359/Node01_201128-103934.log)
[MSCWorldclass_mapsincluded.crash.txt](https://github.com/state-of-the-art/BlendNet/files/5610360/MSCWorldclass_mapsincluded.crash.txt)

**Comment by rabits** [comment]
From the Manager log I see it's completing the first subtask, but for some reason not continue:
```
20.11.28 10:37:34.821000	DEBUG: task MSCWorldclassmapsincluded-2011280934-51-HO4_0 state changed: COMPLETED
20.11.28 10:37:34.825000	DEBUG: Retreive details about the task MSCWorldclassmapsincluded-2011280934-51-HO4_0 execution
20.11.28 10:37:34.880000	INFO: The agent task MSCWorldclassmapsincluded-2011280934-51-HO4_0 was completed
```
Overall seems because of the agent worker exception the result data was not saved properly so can't be done... In the crash file I see it tries to collect statistics and after that raises the exception. So probably there is some error in the statistics collector for Cycles (this Blender error worth to report btw), but in our case to continue - I could suggest the next workaround:
* Comment the line 85 in file [BlendNet/script-render.py](https://github.com/state-of-the-art/BlendNet/blob/v0.3.4/BlendNet/script-render.py#L85) on your Agent node:
   ```python
   try:
       import _cycles
       #_cycles.enable_print_stats() # Show detailed render statistics after the render
   except:
       pass
   ```
After that please retry to render the scene again and attach the usual logs if you will still see some issues.

**Comment by gponceau** [comment]
Thank you. I try what you said and there are some progress. Now I have the same problem than the cube scene with the Error instead of infinite running scene. Here are the log you asked : 
[blendnet-test-manager_201201-114750.log](https://github.com/state-of-the-art/BlendNet/files/5621967/blendnet-test-manager_201201-114750.log)
[Node01_201201-114814.log](https://github.com/state-of-the-art/BlendNet/files/5621968/Node01_201201-114814.log)

It will with pleasure I said to Blender about the crash file but I don't understand anything at all (I'm not a developper and I'm not very at ease with english and log on Blender ^^ It's already difficult to follow this problem for me ^^')

**Comment by gponceau** [comment]
And I tried to delete line 247-250 from BlendNet/ManagerTask.py to resolve the problem like you propose to do previously for the cube scene and it crashed the Manager and Agent so it didnt' work...

**Comment by rabits** [comment]
So the Manager reached the compositing stage - it's quite near the done definition) But looks like the Manager still uses 0.3.3 version, because I see quite the same error we saw earlier:
```
20.12.01 11:41:38.885000	ERROR: Exception occurred during composing the result for task "MSCWorldclassmapsincluded-2012011038-51-qzD": 'utf-8' codec can't decode byte 0x82 in position 84: invalid start byte
```

Could you please ensure you using the [latest release v0.3.4](https://github.com/state-of-the-art/BlendNet/releases/download/v0.3.4/blendnet-0.3.4.zip) for all the BlendNet components: Addon, Manager and Agent - it contains all the required fixes (but the last one with commenting the `_cycles.enable_print_stats()` - you still need to have it for the Agent).

So the actions needed to check:
1. Replace BlendNet on all the instances to the [latest release v0.3.4](https://github.com/state-of-the-art/BlendNet/releases/download/v0.3.4/blendnet-0.3.4.zip)
2. On the Agent comment `_cycles.enable_print_stats()` as described here: https://github.com/state-of-the-art/BlendNet/issues/119#issuecomment-735340495
3. Restart the components of BlendNet and run the rendering again

**Comment by gponceau** [comment]
Hi,
I did a clean installation with Blendnet 0.3.4 and it didn't change anything. Here is the log after the clean reinstallation : 
[blendnet-test-manager_201202-111640.log](https://github.com/state-of-the-art/BlendNet/files/5628519/blendnet-test-manager_201202-111640.log)
[NODE-01_201202-111837.log](https://github.com/state-of-the-art/BlendNet/files/5628520/NODE-01_201202-111837.log)
 
To remind you, the new version 0.3.4 didn't resolve the issue on my cube scene neither : 
https://github.com/state-of-the-art/BlendNet/issues/119#issuecomment-730229939

**Comment by rabits** [comment]
Ok, so there is something I missed... The error with utf-8 decode had to be solved already, but it seems not solved. I think it happened in the same place, so added another catcher and slightly improved the error message - could you please try with this new dev version: https://948-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.5-8114caa.zip on the Manager?

If it will not fix the issue - at least it will show what the exception is actually there) Sorry to waste so much time on that - just hard to reproduce your environment to test those things properly...

**Comment by gponceau** [comment]
Ahah ! ^^ Don't worry, I have time ;-) It's already very nice from you to help me made that work. So I install your new version on manager and agent, and here are the log : 
[blendnet-test-manager_201203-151355.log](https://github.com/state-of-the-art/BlendNet/files/5636605/blendnet-test-manager_201203-151355.log)
[NODE-01_201203-151412.log](https://github.com/state-of-the-art/BlendNet/files/5636606/NODE-01_201203-151412.log)

**Comment by rabits** [comment]
Oh, sorry, you updated Agent, so you still need to comment the statistics as described here: https://github.com/state-of-the-art/BlendNet/issues/119#issuecomment-735340495 - the Agent again failed with crash because of that...

**Comment by rabits** [comment]
I think I need to make it optional, since it's unstable for some cases and probably not useful much for the end user.

**Comment by gponceau** [comment]
Oh ! Sorry ! I misunderstood... I thought you did that ine the version you send to me. Sorry. So here are the new logs with correction.
[NODE-01_201205-171704.log](https://github.com/state-of-the-art/BlendNet/files/5647365/NODE-01_201205-171704.log)
[blendnet-test-manager_201205-171654.log](https://github.com/state-of-the-art/BlendNet/files/5647366/blendnet-test-manager_201205-171654.log)

**Comment by rabits** [comment]
Oh, just realized that I did not sent the message waiting for the tests to complete! Here is it:

Hmmm, this is my bad:
```
ERROR: Exception occurred during composing the result for task "MSCWorldclassmapsincluded-2012051612-51-FVG": <class 'AttributeError'>: 'str' object has no attribute 'decode'
```
Looks like I tried to decode twice, probably my dual stderr/stdout decode optimization is not working well there)

The new dev dist (in addition to the fix I commented out the cycles statistics): https://966-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.5-bd29c31.zip - could you please update Manager and check again?

**Comment by rabits** [comment]
Great! It took some time but finally we made it) So will release the new 0.3.5 today along with the fix. Thank you for your patience and great help)

**Comment by gponceau** [comment]
Thank you again ! And just to know (maybe it’s not the place to ask), is there a way to have manager and agent running simultaneously on a single computer ?

**Comment by rabits** [comment]
Yeah, for such questions is better to join gitter chat https://gitter.im/state-of-the-art/BlendNet , but overall yeah all the components can be running on the same machine. The only thing the can fight for is the network binding port (they uses 8443 and 9443 TCP by default) and a little bit for cpu and memory.
